### ISSUE TITLE
Missing copyright holder in license

### ISSUE THREAD

**Issue by mathisloge** [commschamp/commsdsl#13]
Hi Alex,
the license is missing the copyright holder.

https://github.com/commschamp/commsdsl/blob/ba636a97316210beabcb8e27e15a10fa198d10d9/LICENSE.txt#L190

**Comment by arobenko** [comment]
Strange, must have accidentally deleted the line at some stage. I'll put it back in.
Thanks

**Comment by arobenko** [comment]
Sorry Mathis,
I probably misunderstood you, I thought you meant license text is incomplete. The license text is fine, just copy-pasted from https://www.apache.org/licenses/LICENSE-2.0.txt. 
You need to clarify what you actually mean, what exactly is missing and where?

**Comment by mathisloge** [comment]
Hi Alex,

Shouldn't your name and the year be present in line 190 of the license.

In the comment section before line 190 it said that the `Copyright [yyyy] [name of copyright owner]` should not be copied but replaced.

**Comment by arobenko** [comment]
Hi Mathis,

To apply the Apache License to your work, **attach** the following boilerplate notice, with the fields enclosed by brackets "[]"       replaced with your own identifying information. (Don't include the brackets!)  The text should be enclosed in the appropriate     **comment syntax** for the file format. (emphasis is mine)

Every source file in this repository contains the copyright notice with my name in it alongside with the license declaration header. I don't think I need to change the license text itself.

**Comment by mathisloge** [comment]
Hi Alex,
yes, you're right. I misinterpreted or rather misunderstood that. I've taken a look at some offical apache projects and it's the same there. Sorry for the confusion!
