### ISSUE TITLE
Bit Order in `<bitfield>` and `<set>`

### ISSUE THREAD

**Issue by bearbattle** [commschamp/commsdsl#17]
I've defined a `<bitfield>` in the XML.

![image](https://user-images.githubusercontent.com/48974238/219348166-0f089cf7-b4f5-4db2-8664-bb5e5ff2bb59.png)

As I set flag `F` to `true`, this is what I get in Wireshark:

![image](https://user-images.githubusercontent.com/48974238/219349574-985aea53-587d-43d4-8305-a9a86f335148.png)

With `endian="big"`, this is what I get:

![image](https://user-images.githubusercontent.com/48974238/219349710-83acbfe5-97be-4ec4-ae34-c448465839fc.png)

Another thing is when I try to modify the value of `UnitNum` field, I actually change the value of `PXNum` field.

With `msg.field_annFlags().field_unitNum().value() = 1`:

![image](https://user-images.githubusercontent.com/48974238/219350432-64f8caf2-e98b-43d7-8948-6092cbd0ad6a.png)

How to alter the *bit* order of generated packet data?

**Comment by arobenko** [comment]
Hi @bearbattle,
I think your mental model of the bitfields as well as endian setting is incorrect.

When you specify members of the `<bitfield>` the order of the members is starting with the LSB first, so when you think of your `AnnFlags` as a 16 bit number representation it is encoded as:
```
MSB -> [PXNum (4 bits) | UnitNum (4 bits) | Flags (8 bits)] <- LSB
```
The bit ordering of the `<set>` is also always starting from LSB, i.e bit 0 has mask 0x1 (`1 << 0`), bit 1 has mask 0x2 (`1 << 1`), bit 2 has mask 0x4 (`1 << 2`), etc...

In other words, if your `Flags.F` is set to 1, `UnitNum` is set to 2, and `PXNum` is set to 3, then the 16 bit of the `AnnField` is going to be `0x3201`.

The endian specifies the order of written **bytes**, not **bits**, i.e the two bytes above can be written in only 2 ways:

- `0x32 0x01` - for big endian
- `0x01 0x32` - for little endian

That's all. If you need to serialize it in different way, then you need to re-order your `<bitfield>` and/or use different `idx` property value for your bits. For example if you need your bit `F` to come first (be MSB), then it needs to have `idx="7"`.

Hope it helps.
Regards,
Alex

**Comment by bearbattle** [comment]
Thank you. Will the library provide any methods to alter the bit order (i.e. from MSB to LSB)?

**Comment by arobenko** [comment]
Hi @bearbattle,
Counting (indexing) bits from MSB is **NOT** a common practice in software engineering. I do not intend to do it. It will introduce too much complexity with too little benefit. Re-ordering of the bits is completely within your control when defining the protocol schema, just assign appropriate **idx** value, such as
```xml
<set name="Flags" ...>
    <bit name="F" idx="7" />
    <bit name="K" idx="6" />
    <bit name="P" idx="5" />
    <bit name="C" idx="4" />
</set>
```
Note that the order of the `<bit>`-s definition doesn't have to be from lowest **idx** to the highest. It can be arbitrary, what important is setting the right **idx** value.

**Comment by bearbattle** [comment]
Thanks for your reply! I'm closing the issue.
