### ISSUE TITLE
Schema name cannot start with a capital

### ISSUE THREAD

**Issue by TimonTerBraak** [commschamp/commsdsl#24]
I have had an issue with two different protocol definitions where I started the name of the schema file with a capital letter. This is in contrast with the given examples in the documentation and should not be a limitation:

![image](https://github.com/commschamp/CommsDSL-Specification/assets/1520478/eabdfb01-32a5-4cbd-a011-9ee170f0addb)

The generated code wants to refer to the namespace that is defined by the schema name. However, the namespace starts with a lowercase letter:

![image](https://github.com/commschamp/CommsDSL-Specification/assets/1520478/7a6f8d22-444f-4d82-ab63-d4e36e9793a9)

The resulting compilation errors are also not that obvious, since template issues can cause quite a lenghty report.

**Comment by arobenko** [comment]
What version of the code generator are you using? The latest v6.2.4 should properly support capitalized namespaces. If not, please provide a minimal schema snippet that reproduces the problem.

**Comment by TimonTerBraak** [comment]
Mmm. When I discovered commsdsl I first used it as a submodule in my git-based project. Recently I switched commsdsl over to vcpkg, which still uses version 4.0.0. So, it might very well be that it is no longer an issue in more recent released versions.

Too bad, I really enjoy using vcpkg to manage all my C++ dependencies. They should update their commschamp versions. I will see if there is a way to update those, either locally or poking some package maintainer.

There are still some (outdated) issues that already ask for version updates:
https://github.com/microsoft/vcpkg/pull/19581

**Comment by arobenko** [comment]
I created and maintain [vcpkg ports overlay](https://github.com/commschamp/cc.vcpkg) repository that contains some of the projects developed under the [CommsChampion Eocosystem](https://commschamp.github.io/) umbrella. It is under my control and I update it quite regularly to use the latest releases (next one is planned to come out within a week). If I'm not mistaken @mathisloge is a person who originally introduced [comms](https://github.com/commschamp/comms) library and [commsdsl](https://github.com/commschamp/commsdsl) code generators to upstream vcpkg. Ideally I would prefer the packages to be removed from the vcpkg upstream to avoid future confusion, but I'm not sure about the procedure and whether such even exists. I'm not a vcpkg user myself (I'm an embedded C++ developer and mostly use [buildroot](https://github.com/commschamp/cc.buildroot/) and [yocto](https://github.com/commschamp/meta-commschamp)) and would prefer if someone else put an effort in to do it as well as take proper "ownership" of what's going on inside the [cc.vcpkg](https://github.com/commschamp/cc.vcpkg) repository.

Also please refer to the [projects](https://commschamp.github.io/projects/) page for a full list of CommsChampion Ecosystem projects I develop and maintain.

**Comment by TimonTerBraak** [comment]
I did not know about the existence of the vcpkg ports overlay repository. Yesterday I figured out how to create a (filesystem based) vcpkg repository, in which I updates the versions. It worked as expected, so it’s a fine solution for me. Maybe I’ll switch to the repository at some point.
