### ISSUE TITLE
noexcept error with gcc 9

### ISSUE THREAD

**Issue by benguela** [commschamp/commsdsl#3]
First off, I have been using commschampion ecosystem for a few months, excellent product, thank you!

With the latest ubuntu release 19.10, gcc has been upgraded to version 9, in my case 9.2.1.
commsdsl now throws this error when building

commsdsl/build/commsdsl/src/lib/src/NamespaceImpl.cpp: In constructor ‘commsdsl::NamespaceImpl::NamespaceImpl(xmlNodePtr, commsdsl::ProtocolImpl&)’:
commsdsl/build/commsdsl/src/lib/src/NamespaceImpl.cpp:72:24: error: noexcept-expression evaluates to ‘false’ because of a call to ‘static constexpr unsigned int commsdsl::Protocol::notYetDeprecated()’ [-Werror=noexcept]
   72 |     m_protocol(protocol)
      |                        ^

**Comment by arobenko** [comment]
Thanks for the report. I'll take a look within next couple of days.

**Comment by arobenko** [comment]
The fix to commsdsl is quite trivial, however COMMS library itself requires several minor fixes to properly support gcc-9. I'll do the correction release to the comms_champion project first within a week or so.

**Comment by arobenko** [comment]
Status update: The fixes are available on "develop" branch, which currently also requires usage of "develop" branch of the [comms_champion](https://github.com/arobenko/comms_champion) project. The correction release v2.2.1 of the latter with all the required fixes will be done some time next week. The update to commsdsl project will follow shortly after that.

**Comment by arobenko** [comment]
Fixed in recently released v3.1

**Comment by benguela** [comment]
thanks. confirmed it works on my box
