### ISSUE TITLE
error when using COMMSDSL_NO_TESTS

### ISSUE THREAD

**Issue by mathisloge** [commschamp/commsdsl#7]
When setting the option `COMMSDSL_NO_TESTS` to true, the tests in lib/test cmake are still executed. 
setting BUILD_TESTING to false if COMMSDSL_NO_TESTS is true fixes the issue for me

**Comment by arobenko** [comment]
Sorry, cannot reproduce on clean build. The call to [cc_get_cxxtest](https://github.com/commschamp/commsdsl/blob/master/CMakeLists.txt#L64) will result in execution of [include(CTest)](https://github.com/commschamp/comms_champion/blob/master/cmake/CC_CxxtestFuncs.cmake#L132), which in turn executes `enable_testing()`, which in turn defines `BUILD_TESTING`. It's documented [here](https://cmake.org/cmake/help/latest/command/enable_testing.html).

Setting of the COMMSDSL_NO_TESTS is expected to skip this chain of events and as the result `BUILD_TESTING` should not be defined.

Maybe try to do a complete clean build by removing the build directory as well as "externals" one.

**Comment by mathisloge** [comment]
yep, removing the externals one fixed it. Sorry!
